package freezy.freezy_be.productTemplates;


import com.github.javafaker.Faker;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(1)
public class ProductTemplateRunner implements CommandLineRunner {

    @Autowired
    private ProductTemplateRepository productTemplateRepository;

    @Override
    public void run(String... args) throws Exception {
        if (productTemplateRepository.count() == 0) {
            ProductTemplateRepository repository = productTemplateRepository;
            repository.save(new ProductTemplate("Insalata", "Lava e asciuga bene le foglie, poi conservale in frigorifero avvolte in un panno da cucina leggermente umido per mantenerle fresche più a lungo.", TipoProdotto.VERDURA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw6c7cc053/large/InsalatascarolasfusacategoriaI-2133270000000-1.jpg"));
            repository.save(new ProductTemplate("Bistecca", "Conserva la bistecca in frigorifero a una temperatura tra 0°C e 4°C, preferibilmente avvolta in carta da macellaio o in un contenitore ermetico.", TipoProdotto.CARNE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwd89261ca/large/costata_con_osso1.jpg"));
            repository.save(new ProductTemplate("Petto di Pollo", "Riponi il petto di pollo in frigorifero entro un'ora dall'acquisto, conservandolo in un contenitore ermetico o avvolto in pellicola trasparente.", TipoProdotto.CARNE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw1a262da7/large/PettodiPolloafetteconfezionerisparmio-2001528000000-1.jpg"));
            repository.save(new ProductTemplate("Salsiccia", "Conserva le salsicce in frigorifero, preferibilmente nella parte più fredda, e consumale entro la data di scadenza indicata.", TipoProdotto.CARNE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw3b30d213/large/Salsicciadisuinoconfinocchio-2217496000000-1.jpg"));
            repository.save(new ProductTemplate("Prosciutto crudo", "Avvolgi il prosciutto crudo in carta oleata e conservalo in frigorifero, preferibilmente nel cassetto delle verdure.", TipoProdotto.CARNE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw3b24368e/large/ProsciuttoToscanoDOPTerredItaliadabanco-2115119000000-1.jpg"));
            repository.save(new ProductTemplate("Mortadella", "Conserva la mortadella in frigorifero avvolta in pellicola trasparente o in un contenitore ermetico per mantenere la freschezza.", TipoProdotto.CARNE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw3977a17e/large/MORTADPISTACCHIOTDIMECPALM-2087339000000-1.jpg"));
            repository.save(new ProductTemplate("Parmigiano Reggiano", "Avvolgi il Parmigiano in carta oleata e conservalo nella parte meno fredda del frigorifero per evitare che si secchi.", TipoProdotto.FORMAGGIO, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwea2e4a11/large/ParmigianoReggianodimontagnaDOP24mesiFilieraQualitaCarrefour-2117873000000-1.jpg"));
            repository.save(new ProductTemplate("Mozzarella", "Conserva la mozzarella nel suo liquido di governo in frigorifero e consumala entro pochi giorni dall'apertura.", TipoProdotto.FORMAGGIO, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwef5fb0fc/large/Mozzarella100ItalianaGranaroloConf3pzg100Cad300g-8002670007640-1.jpg"));
            repository.save(new ProductTemplate("Gorgonzola", "Avvolgi il Gorgonzola in carta stagnola e conservalo in frigorifero, preferibilmente nel cassetto delle verdure.", TipoProdotto.FORMAGGIO, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw74faca79/large/GorgonzolaDolceDOPSfiziosodabanco-2046047000000-1.jpg"));
            repository.save(new ProductTemplate("Ricotta", "Conserva la ricotta in frigorifero in un contenitore ermetico e consumala entro pochi giorni dall'apertura.", TipoProdotto.FORMAGGIO, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/dw/image/v2/BDWP_PRD/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw22904927/large/RICOTTACRFGR250-8012666008414-1.png"));
            repository.save(new ProductTemplate("Provolone", "Avvolgi il Provolone in carta oleata e conservalo nella parte meno fredda del frigorifero per preservarne il sapore.", TipoProdotto.FORMAGGIO, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwbaca7a0e/large/ScamorzaaffumicataSabellidabanco-2047221000000-1.jpg"));
            repository.save(new ProductTemplate("Tonno in scatola", "Una volta aperta la scatoletta, trasferisci il tonno in un contenitore ermetico e conservalo in frigorifero per un massimo di 2 giorni.", TipoProdotto.SCATOLETTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw7d416e52/large/TONNOOOFILODOLIORMX4-8004030104006-1.png"));
            repository.save(new ProductTemplate("Piselli in scatola", "Dopo l'apertura, trasferisci i piselli in un contenitore ermetico e conservali in frigorifero per un massimo di 2 giorni.", TipoProdotto.SCATOLETTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/dw/image/v2/BDWP_PRD/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw57f15aaf/large/PISELLIMEDICRF-3560071222307-1.png"));
            repository.save(new ProductTemplate("Fagioli in scatola", "Una volta aperta la scatola, trasferisci i fagioli in un contenitore ermetico e conservali in frigorifero per un massimo di 2 giorni.", TipoProdotto.SCATOLETTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwf2b8f97d/large/BIOFAGIOLICANNELLINICRF-8012666040131-1.png"));
            repository.save(new ProductTemplate("Mais in scatola", "Dopo l'apertura, trasferisci il mais in un contenitore ermetico e conservalo in frigorifero per un massimo di 2 giorni.", TipoProdotto.SCATOLETTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwbb5a58c7/large/MAISSZUCCHEROAGGIUNTOCRF-3560071213350-1.png"));
            repository.save(new ProductTemplate("Pomodori", "una volta acquistati inserirli in una vaschetta e metterli all'interno del frigorifero", TipoProdotto.VERDURA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/dw/image/v2/BDWP_PRD/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwe87a7c63/large/POMODDATTERINOSNICKELG250-8056446330005-1.png"));
            repository.save(new ProductTemplate("Mela", "Conserva le mele in frigorifero per prolungarne la freschezza, evitando di tenerle vicino ad altri frutti per prevenire la maturazione accelerata.", TipoProdotto.FRUTTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw67c6fbdf/large/MeleFujiFQC1kgItaliaIcategoriacalibro80858590-2014945000000-1.jpg"));
            repository.save(new ProductTemplate("Banana", "Conserva le banane a temperatura ambiente, lontano dalla luce diretta del sole, e separale da altri frutti per evitare la maturazione accelerata.", TipoProdotto.FRUTTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw924aaaec/large/BANANEGR600-0000054001978-1.jpg"));
            repository.save(new ProductTemplate("Arancia", "Conserva le arance in un luogo fresco e asciutto, lontano dalla luce diretta del sole, per mantenerle fresche più a lungo.", TipoProdotto.FRUTTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwdf12850e/large/ARANCENAVELINASKG3-8058056570765-1.jpg"));
            repository.save(new ProductTemplate("Kiwi", "Conserva i kiwi in frigorifero per prolungarne la freschezza, evitando di tenerli vicino ad altri frutti per prevenire la maturazione accelerata.", TipoProdotto.FRUTTA, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw74edde6d/large/KIWISFFQC-2014946000000-1.jpg"));
            repository.save(new ProductTemplate("Salmone", "Conserva il salmone in frigorifero per prolungarne la freschezza.", TipoProdotto.PESCE, UnitaDiMisura.GRAMMI, "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dwa9456651/large/SALMONE3420KG-2061460000000-1.jpg"));
        }
    }
}
